version: '3.5'

services:
  agd:
    container_name: "${CONTAINER_NAME}"
    image: ghcr.io/agoric/agoric-3-proposals:main
    platform: linux/amd64
    ports:
      - 26656
      - 26657
      - 1317
    environment:
      DEBUG: "SwingSet:ls,SwingSet:vat"
    entrypoint: /usr/src/upgrade-test-scripts/start_agd.sh

